language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pip install -U tox pytest pytest-cov codecov
  - pip install -r requirements_dev.txt

script: tox -e ${TOXENV}

after_success:
  - codecov