dist: trusty
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27

install: pip install -U tox

script: tox -e ${TOXENV}